spring:
  config:
    activate:
      on-profile: "local"
  datasource:
    driver-class-name: "com.mysql.cj.jdbc.Driver"
    url: "jdbc:mysql://localhost:3306/scot?useSSL=false&characterEncoding=UTF-8&serverTimezone=UTC"
    username: "scot"
    password: "scot123!@#"
  jpa:
    properties:
      hibernate:
        format_sql: true
        ddl-auto: create
    database: mysql
    database-platform: org.hibernate.dialect.MySQL5InnoDBDialect
    generate-ddl: true
    show-sql: true
  auth:
    code-url: "https://kauth.kakao.com/oauth/authorize"
    token-url: "https://kauth.kakao.com/oauth/token"
    user-url: "https://kapi.kakao.com/v2/user/me"
    logout-url: "https://kapi.kakao.com/v1/user/logout"
    client-id: "d27b18e9bec54a03247b4f05fa805d3f"
    client-secret: "NNKvZ5HylMXGdlJ3sgQ55UwG7nXp3zLy"
    jwt-key: "scot_secret_j21j5j3k5i53g46g56u63g3u4h43h435ugh3"
    jwt-expire-in-seconds: 120
    callback-url: "http://localhost:8089/v1/auth/callback"
    client-redirect-url: "http://localhost:3000"

